name: build-unstable

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

jobs:
  build-cli:
    name: Build catalog CLI tool

    strategy:
      matrix:
        os: [ubuntu-latest]
        version:
          - ${{ github.ref_name || 'unstable' }}
        target:
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: |
          cd cli
          deno compile --allow-read -o fig-${{ matrix.target }}-${{ matrix.version }} main.ts

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fig-${{ matrix.target }}-${{ matrix.version }}
          path: cli/fig-${{ matrix.target }}-${{ matrix.version }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cli/fig-${{ matrix.target }}-${{ matrix.version }}${{ matrix.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
          latest: true
